const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const{randomBytes}=require('node:crypto');
const bcrypt=require('bcryptjs');const{before,after,test}=require('node:test');const assert=require('node:assert/strict');
const{initializeDatabase,MIGRATION_VERSION}=require('../src/db/connection');const{createAdministrator}=require('../src/scripts/createAdmin');const{createConfig}=require('../src/config');const{createApp}=require('../src/app');

const secret=(label)=>`${label}!Aa1${randomBytes(16).toString('hex')}`;const ADMIN_PASSWORD=secret('admin'),STUDENT_PASSWORD=secret('student'),TEACHER_PASSWORD=secret('teacher');
let temporaryDirectory,databasePath,db,server,baseUrl,adminToken,studentToken,teacherToken,route,bus,driver,employee,contact,draftTrip,approvedTrip,feedback;
async function request(pathname,{method='GET',token,body,headers={}}={}){const requestHeaders={Accept:'application/json',...headers};if(token)requestHeaders.Authorization=`Bearer ${token}`;if(body!==undefined)requestHeaders['Content-Type']='application/json';const response=await fetch(`${baseUrl}${pathname}`,{method,headers:requestHeaders,body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));return{response,payload};}
const schedule=(overrides={})=>({route_id:route.id,bus_id:bus.id,driver_id:driver.id,service_date:'2099-09-20',departure_time:'09:00',arrival_time:'10:00',notes:'Fictional Phase 4 operation.',...overrides});
const trip=(overrides={})=>({category:'EXAM',title:'Fictional Examination Shuttle',description:'Synthetic operational test trip.',organizer:'Fictional Academic Office',schedule:schedule(),...overrides});

before(async()=>{temporaryDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'diu-transport-phase4-api-'));databasePath=path.join(temporaryDirectory,'api.db');db=initializeDatabase(databasePath);
  for(const[email,role,password,name]of[['phase4.student@example.test','STUDENT',STUDENT_PASSWORD,'Fictional Student One'],['phase4.student2@example.test','STUDENT',STUDENT_PASSWORD,'Fictional Student Two'],['phase4.teacher@example.test','TEACHER',TEACHER_PASSWORD,'Fictional Teacher One']])db.prepare('INSERT INTO users(full_name,email,password_hash,role) VALUES(?,?,?,?)').run(name,email,bcrypt.hashSync(password,4),role);
  createAdministrator(db,{fullName:'Fictional Phase Four Administrator',email:'phase4.admin@example.test',password:ADMIN_PASSWORD});
  route={id:Number(db.prepare("INSERT INTO routes(route_name,origin,destination) VALUES('Phase Four Route','Synthetic North','Synthetic South')").run().lastInsertRowid)};bus={id:Number(db.prepare("INSERT INTO buses(bus_number,capacity) VALUES('P4-BUS-001',40)").run().lastInsertRowid)};driver={id:Number(db.prepare("INSERT INTO drivers(full_name,phone) VALUES('Fictional Phase Four Driver','000-000-4001')").run().lastInsertRowid)};
  const config=createConfig({env:{NODE_ENV:'test',PORT:'0',CLIENT_ORIGIN:'http://approved.test',WEB_DATABASE_PATH:databasePath,AUTH_SECRET:randomBytes(48).toString('hex'),AUTH_EXPIRES_IN:'10m',PUBLIC_REGISTRATION_ROLES:'STUDENT,TEACHER',AUTH_RATE_LIMIT_WINDOW_MS:'60000',AUTH_RATE_LIMIT_MAX:'100',API_RATE_LIMIT_WINDOW_MS:'60000',API_RATE_LIMIT_MAX:'1000',FEEDBACK_RATE_LIMIT_WINDOW_MS:'60000',FEEDBACK_RATE_LIMIT_MAX:'100',TRUST_PROXY:'false',AUDIT_PAGE_SIZE_MAX:'100',NOTIFICATION_PAGE_SIZE_MAX:'100',FEEDBACK_PAGE_SIZE_MAX:'100',SPECIAL_TRIP_PAGE_SIZE_MAX:'100',BACKUP_DIRECTORY:path.join(temporaryDirectory,'backups'),EXPORT_DIRECTORY:path.join(temporaryDirectory,'exports')}});
  server=createApp({db,config}).listen(0);await new Promise((resolve)=>server.once('listening',resolve));baseUrl=`http://127.0.0.1:${server.address().port}`;
  for(const[email,password,key]of[['phase4.admin@example.test',ADMIN_PASSWORD,'admin'],['phase4.student@example.test',STUDENT_PASSWORD,'student'],['phase4.teacher@example.test',TEACHER_PASSWORD,'teacher']]){const token=(await request('/api/auth/login',{method:'POST',body:{email,password}})).payload.token;if(key==='admin')adminToken=token;if(key==='student')studentToken=token;if(key==='teacher')teacherToken=token;}
});
after(async()=>{if(server)await new Promise((resolve)=>server.close(resolve));if(db?.open)db.close();if(temporaryDirectory?.startsWith(os.tmpdir()))fs.rmSync(temporaryDirectory,{recursive:true,force:true});});

test('Phase 4 schema is current and foreign keys remain enabled',()=>{assert.equal(MIGRATION_VERSION,3);assert.equal(db.pragma('foreign_keys',{simple:true}),1);for(const table of['employees','special_trips','notifications','notification_reads','emergency_contacts','feedback'])assert.ok(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name=?").get(table));});
test('Phase 4 mutations require an administrator',async()=>{for(const endpoint of['employees','special-trips','notifications','contacts']){assert.equal((await request(`/api/${endpoint}`)).response.status,401);assert.equal((await request(`/api/${endpoint}`,{method:'POST',token:studentToken,body:{}})).response.status,403);}assert.equal((await request('/api/admin/feedback',{token:studentToken})).response.status,403);});

test('administrator creates and updates a validated employee',async()=>{let result=await request('/api/employees',{method:'POST',token:adminToken,body:{employee_code:' p4-emp-001 ',full_name:'Fictional Transport Officer',employee_role:'TRANSPORT_OFFICER',phone:'000-000-4100',email:'officer@example.test',shift:'MORNING',notes:'Synthetic record.'}});assert.equal(result.response.status,201);employee=result.payload.data;assert.equal(employee.employee_code,'P4-EMP-001');result=await request(`/api/employees/${employee.id}`,{method:'PATCH',token:adminToken,body:{shift:'EVENING'}});assert.equal(result.response.status,200);assert.equal(result.payload.data.shift,'EVENING');});
test('employee duplicates, invalid fields, and public private-data exposure are rejected',async()=>{assert.equal((await request('/api/employees',{method:'POST',token:adminToken,body:{employee_code:'p4-emp-001',full_name:'Duplicate Fictional',employee_role:'HELPER',phone:'000-000-4101',shift:'NIGHT'}})).response.status,409);for(const body of[{employee_code:'P4-BAD-1',full_name:'X',employee_role:'HELPER',phone:'000-000-4101',shift:'NIGHT'},{employee_code:'P4-BAD-2',full_name:'Fictional Helper',employee_role:'DRIVER',phone:'000-000-4101',shift:'NIGHT'},{employee_code:'P4-BAD-3',full_name:'Fictional Helper',employee_role:'HELPER',phone:'secret',shift:'NIGHT'},{employee_code:'P4-BAD-4',full_name:'Fictional Helper',employee_role:'HELPER',phone:'000-000-4101',shift:'DAY'}])assert.equal((await request('/api/employees',{method:'POST',token:adminToken,body})).response.status,400);const list=await request('/api/employees',{token:studentToken});assert.equal(list.response.status,200);assert.equal('phone'in list.payload.data[0],false);assert.equal('email'in list.payload.data[0],false);});
test('employee deactivation preserves history and supports explicit reactivation',async()=>{let result=await request(`/api/employees/${employee.id}`,{method:'DELETE',token:adminToken});assert.equal(result.payload.data.status,'INACTIVE');assert.equal((await request('/api/employees',{token:studentToken})).payload.data.some((item)=>item.id===employee.id),false);result=await request(`/api/employees/${employee.id}/reactivate`,{method:'POST',token:adminToken});assert.equal(result.payload.data.status,'ACTIVE');});

test('administrator manages ordered emergency contacts while users see active contacts',async()=>{let result=await request('/api/contacts',{method:'POST',token:adminToken,body:{contact_name:'Fictional Emergency Desk',contact_role:'EMERGENCY_HOTLINE',phone:'000-000-4200',email:'desk@example.test',availability:'24-hour synthetic coverage',display_order:2}});assert.equal(result.response.status,201);contact=result.payload.data;result=await request(`/api/contacts/${contact.id}`,{method:'PATCH',token:adminToken,body:{display_order:1}});assert.equal(result.payload.data.display_order,1);assert.ok((await request('/api/contacts',{token:studentToken})).payload.data.some((item)=>item.id===contact.id));});
test('contact validation and safe deactivate/reactivate behavior work',async()=>{assert.equal((await request('/api/contacts',{method:'POST',token:adminToken,body:{contact_name:'Bad',contact_role:'INVALID',phone:'x',availability:'x'}})).response.status,400);assert.equal((await request(`/api/contacts/${contact.id}`,{method:'DELETE',token:adminToken})).payload.data.status,'INACTIVE');assert.equal((await request('/api/contacts',{token:studentToken})).payload.data.some((item)=>item.id===contact.id),false);assert.equal((await request(`/api/contacts/${contact.id}/reactivate`,{method:'POST',token:adminToken})).payload.data.status,'ACTIVE');});

test('manual notification drafts stay private until published',async()=>{let result=await request('/api/notifications',{method:'POST',token:adminToken,body:{title:'Fictional Service Notice',message:'Synthetic service information.',notification_type:'GENERAL',status:'DRAFT'}});assert.equal(result.response.status,201);const notice=result.payload.data;assert.equal((await request('/api/notifications',{token:studentToken})).payload.data.some((item)=>item.id===notice.id),false);result=await request(`/api/notifications/${notice.id}/publish`,{method:'POST',token:adminToken});assert.equal(result.payload.data.status,'PUBLISHED');assert.ok((await request('/api/notifications',{token:studentToken})).payload.data.some((item)=>item.id===notice.id));});
test('role-specific notifications and per-user read state are isolated',async()=>{const notice=(await request('/api/notifications',{method:'POST',token:adminToken,body:{title:'Student-only Notice',message:'Visible only to fictional students.',notification_type:'GENERAL',audience_role:'STUDENT',status:'PUBLISHED'}})).payload.data;assert.ok((await request('/api/notifications',{token:studentToken})).payload.data.some((item)=>item.id===notice.id));assert.equal((await request('/api/notifications',{token:teacherToken})).payload.data.some((item)=>item.id===notice.id),false);const read=await request(`/api/notifications/${notice.id}/read`,{method:'POST',token:studentToken});assert.equal(read.payload.data.is_read,1);const secondUserId=db.prepare("SELECT id FROM users WHERE email='phase4.student2@example.test'").get().id;assert.equal(db.prepare('SELECT 1 FROM notification_reads WHERE notification_id=? AND user_id=?').get(notice.id,secondUserId),undefined);});
test('notification cancellation, expiry, and transitions are enforced',async()=>{let notice=(await request('/api/notifications',{method:'POST',token:adminToken,body:{title:'Temporary Notice',message:'Synthetic temporary notice.',notification_type:'GENERAL',status:'PUBLISHED'}})).payload.data;assert.equal((await request(`/api/notifications/${notice.id}/expire`,{method:'POST',token:adminToken})).payload.data.status,'EXPIRED');assert.equal((await request(`/api/notifications/${notice.id}/publish`,{method:'POST',token:adminToken})).response.status,409);notice=(await request('/api/notifications',{method:'POST',token:adminToken,body:{title:'Cancelled Draft',message:'Synthetic cancelled draft.',notification_type:'GENERAL',status:'DRAFT'}})).payload.data;assert.equal((await request(`/api/notifications/${notice.id}/cancel`,{method:'POST',token:adminToken})).payload.data.status,'CANCELLED');});

test('special trip draft is hidden and supports draft editing',async()=>{let result=await request('/api/special-trips',{method:'POST',token:adminToken,body:trip()});assert.equal(result.response.status,201);draftTrip=result.payload.data;assert.equal(draftTrip.approval_status,'DRAFT');assert.equal(draftTrip.schedule.status,'CANCELLED');assert.equal((await request('/api/special-trips',{token:studentToken})).payload.data.some((item)=>item.id===draftTrip.id),false);result=await request(`/api/special-trips/${draftTrip.id}`,{method:'PATCH',token:adminToken,body:{category:'CLUB_EVENT',title:'Fictional Club Event Shuttle'}});assert.equal(result.payload.data.category,'CLUB_EVENT');});
test('special trip approval reuses schedule assignments and emits an automatic notification',async()=>{const result=await request(`/api/special-trips/${draftTrip.id}/approve`,{method:'POST',token:adminToken,headers:{'X-Request-ID':'phase4-special-approve'}});assert.equal(result.response.status,200);approvedTrip=result.payload.data;assert.equal(approvedTrip.approval_status,'APPROVED');assert.equal(approvedTrip.schedule.status,'ACTIVE');assert.ok((await request('/api/special-trips',{token:studentToken})).payload.data.some((item)=>item.id===approvedTrip.id));assert.ok(db.prepare("SELECT id FROM notifications WHERE related_entity_type='SPECIAL_TRIP' AND related_entity_id=? AND status='PUBLISHED'").get(approvedTrip.id));});
test('special trip bus and driver conflicts fail closed and are audited',async()=>{for(const[title,overrides]of[['Fictional Bus Conflict',{departure_time:'09:15',arrival_time:'09:45'}],['Fictional Driver Conflict',{bus_id:Number(db.prepare("INSERT INTO buses(bus_number,capacity) VALUES('P4-BUS-002',30)").run().lastInsertRowid),departure_time:'09:20',arrival_time:'09:50'}]]){const created=await request('/api/special-trips',{method:'POST',token:adminToken,body:trip({title,schedule:schedule(overrides)})});assert.equal(created.response.status,201);assert.equal((await request(`/api/special-trips/${created.payload.data.id}/approve`,{method:'POST',token:adminToken})).response.status,409);}assert.ok(db.prepare("SELECT COUNT(*) count FROM audit_logs WHERE action='SPECIAL_TRIP_APPROVE' AND outcome='CONFLICT'").get().count>=2);});
test('inactive assignments are rejected and special-trip lifecycle transitions are constrained',async()=>{const inactiveBus=Number(db.prepare("INSERT INTO buses(bus_number,capacity,status) VALUES('P4-INACTIVE',30,'INACTIVE')").run().lastInsertRowid);assert.equal((await request('/api/special-trips',{method:'POST',token:adminToken,body:trip({title:'Fictional Invalid Assignment',schedule:schedule({bus_id:inactiveBus,service_date:'2099-09-21'})})})).response.status,400);assert.equal((await request(`/api/special-trips/${draftTrip.id}/approve`,{method:'POST',token:adminToken})).response.status,409);assert.equal((await request(`/api/special-trips/${approvedTrip.id}/complete`,{method:'POST',token:adminToken})).payload.data.approval_status,'COMPLETED');assert.equal((await request(`/api/special-trips/${approvedTrip.id}/cancel`,{method:'POST',token:adminToken})).response.status,409);});
test('special-trip cancellation preserves the record and emits one cancellation notice',async()=>{const created=(await request('/api/special-trips',{method:'POST',token:adminToken,body:trip({category:'OTHER',title:'Fictional Cancellation Trip',schedule:schedule({service_date:'2099-09-22'})})})).payload.data;assert.equal((await request(`/api/special-trips/${created.id}/approve`,{method:'POST',token:adminToken})).response.status,200);const cancelled=await request(`/api/special-trips/${created.id}/cancel`,{method:'POST',token:adminToken});assert.equal(cancelled.payload.data.approval_status,'CANCELLED');assert.equal(cancelled.payload.data.schedule.status,'CANCELLED');assert.equal(db.prepare("SELECT COUNT(*) count FROM notifications WHERE dedupe_key=?").get(`special-trip:${created.id}:cancelled`).count,1);});
test('schedule updates and cancellations create deduplicated automatic notifications',async()=>{const created=(await request('/api/schedules',{method:'POST',token:adminToken,body:schedule({service_date:'2099-09-23',departure_time:'12:00',arrival_time:'13:00'})})).payload.data;for(const notes of['Synthetic updated schedule note.','Synthetic repeated event update.'])assert.equal((await request(`/api/schedules/${created.id}`,{method:'PATCH',token:adminToken,headers:{'X-Request-ID':'phase4-schedule-update'},body:{notes}})).response.status,200);assert.equal((await request(`/api/schedules/${created.id}`,{method:'DELETE',token:adminToken,headers:{'X-Request-ID':'phase4-schedule-cancel'}})).response.status,200);assert.equal(db.prepare("SELECT COUNT(*) count FROM notifications WHERE related_entity_type='SCHEDULE' AND related_entity_id=? AND notification_type='SCHEDULE_UPDATE'").get(created.id).count,1);assert.equal(db.prepare("SELECT COUNT(*) count FROM notifications WHERE related_entity_type='SCHEDULE' AND related_entity_id=? AND notification_type='SCHEDULE_CANCELLATION'").get(created.id).count,1);});

test('authenticated users submit validated feedback and only see their own records',async()=>{let result=await request('/api/feedback',{method:'POST',token:studentToken,body:{category:'SAFETY',subject:'Fictional Safety Observation',message:'Synthetic feedback with no personal or credential data.'}});assert.equal(result.response.status,201);feedback=result.payload.data;assert.equal(feedback.status,'NEW');assert.equal((await request('/api/feedback')).response.status,401);assert.equal((await request('/api/feedback',{method:'POST',token:studentToken,body:{category:'SAFETY',subject:'Credential',message:'Authorization: Bearer this-is-a-synthetic-token-value'}})).response.status,400);assert.ok((await request('/api/feedback/mine',{token:studentToken})).payload.data.some((item)=>item.id===feedback.id));assert.equal((await request(`/api/feedback/mine/${feedback.id}`,{token:teacherToken})).response.status,404);});
test('administrator filters, assigns, responds to, and resolves feedback',async()=>{let result=await request(`/api/admin/feedback/${feedback.id}`,{method:'PATCH',token:adminToken,body:{status:'IN_REVIEW',assigned_to:employee.id,admin_response:'Synthetic review is underway.'}});assert.equal(result.response.status,200);assert.equal(result.payload.data.status,'IN_REVIEW');assert.equal(result.payload.data.assigned_employee_code,employee.employee_code);result=await request(`/api/admin/feedback/${feedback.id}`,{method:'PATCH',token:adminToken,body:{status:'RESOLVED',admin_response:'Synthetic resolution recorded.'}});assert.equal(result.payload.data.status,'RESOLVED');assert.ok(result.payload.data.resolved_at);const filtered=await request('/api/admin/feedback?status=RESOLVED&category=SAFETY',{token:adminToken});assert.ok(filtered.payload.data.some((item)=>item.id===feedback.id));});
test('feedback transitions and inactive assignees fail closed',async()=>{assert.equal((await request(`/api/admin/feedback/${feedback.id}`,{method:'PATCH',token:adminToken,body:{status:'NEW'}})).response.status,409);await request(`/api/employees/${employee.id}`,{method:'DELETE',token:adminToken});const other=(await request('/api/feedback',{method:'POST',token:teacherToken,body:{category:'APPLICATION',subject:'Fictional Application Feedback',message:'Synthetic application feedback.'}})).payload.data;assert.equal((await request(`/api/admin/feedback/${other.id}`,{method:'PATCH',token:adminToken,body:{assigned_to:employee.id}})).response.status,400);});
test('Phase 4 audit metadata is redacted and request IDs are retained',()=>{const rows=db.prepare("SELECT * FROM audit_logs WHERE entity_type IN ('EMPLOYEE','SPECIAL_TRIP','NOTIFICATION','EMERGENCY_CONTACT','FEEDBACK')").all();assert.ok(rows.length>0);const serialized=rows.map((row)=>row.metadata_json).join(' ').toLowerCase();for(const forbidden of['fictional safety observation','synthetic feedback with','000-000-4100','officer@example.test','authorization','bearer ','password_hash'])assert.equal(serialized.includes(forbidden),false);assert.ok(rows.some((row)=>row.request_id==='phase4-special-approve'));for(const row of rows)assert.doesNotThrow(()=>JSON.parse(row.metadata_json));});
test('feedback rate limiting returns a controlled 429',async()=>{const config=createConfig({env:{NODE_ENV:'test',PORT:'0',CLIENT_ORIGIN:'http://approved.test',WEB_DATABASE_PATH:databasePath,AUTH_SECRET:randomBytes(48).toString('hex'),AUTH_EXPIRES_IN:'10m',PUBLIC_REGISTRATION_ROLES:'STUDENT,TEACHER',AUTH_RATE_LIMIT_WINDOW_MS:'60000',AUTH_RATE_LIMIT_MAX:'100',API_RATE_LIMIT_WINDOW_MS:'60000',API_RATE_LIMIT_MAX:'100',FEEDBACK_RATE_LIMIT_WINDOW_MS:'60000',FEEDBACK_RATE_LIMIT_MAX:'2',TRUST_PROXY:'false',AUDIT_PAGE_SIZE_MAX:'100',NOTIFICATION_PAGE_SIZE_MAX:'100',FEEDBACK_PAGE_SIZE_MAX:'100',SPECIAL_TRIP_PAGE_SIZE_MAX:'100',BACKUP_DIRECTORY:path.join(temporaryDirectory,'backups'),EXPORT_DIRECTORY:path.join(temporaryDirectory,'exports')}});const limited=createApp({db,config}).listen(0);await new Promise((resolve)=>limited.once('listening',resolve));const limitedBase=`http://127.0.0.1:${limited.address().port}`;try{const login=await fetch(`${limitedBase}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'phase4.teacher@example.test',password:TEACHER_PASSWORD})});const token=(await login.json()).token;for(let index=0;index<2;index+=1){const response=await fetch(`${limitedBase}/api/feedback`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({category:'OTHER',subject:`Rate limit ${index}`,message:'Synthetic feedback rate-limit fixture.'})});assert.equal(response.status,201);}const rejected=await fetch(`${limitedBase}/api/feedback`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({category:'OTHER',subject:'Rate limit rejected',message:'Synthetic feedback rate-limit fixture.'})});assert.equal(rejected.status,429);assert.ok((await rejected.json()).request_id);}finally{await new Promise((resolve)=>limited.close(resolve));}});
