const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { randomBytes } = require('node:crypto');
const bcrypt = require('bcryptjs');
const { before, after, test } = require('node:test');
const assert = require('node:assert/strict');
const { initializeDatabase, MIGRATION_VERSION } = require('../src/db/connection');
const { createConfig } = require('../src/config');
const { createApp } = require('../src/app');
const { createAdministrator } = require('../src/scripts/createAdmin');

const password = (label) => `${label}!Aa1${randomBytes(16).toString('hex')}`;
const ADMIN_PASSWORD = password('admin'); const SECOND_ADMIN_PASSWORD = password('second');
const STUDENT_PASSWORD = password('student'); const RECOVERED_PASSWORD = password('recovered');
let dir; let db; let server; let base; let adminToken; let studentToken; let adminId; let secondAdminId; let studentId; let outboxJobId; const logs = [];

async function request(endpoint, { method = 'GET', token, body } = {}) {
  const headers = { Accept: 'application/json' }; if (token) headers.Authorization = `Bearer ${token}`; if (body !== undefined) headers['Content-Type'] = 'application/json';
  const response = await fetch(`${base}${endpoint}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const payload = await response.json(); return { response, payload };
}
async function login(email, value) { return request('/api/auth/login', { method: 'POST', body: { email, password: value } }); }

before(async () => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'diu-phase5-api-')); const databasePath = path.join(dir, 'phase5.db'); db = initializeDatabase(databasePath);
  createAdministrator(db, { fullName: 'Fictional Primary Administrator', email: 'primary.admin@example.test', password: ADMIN_PASSWORD });
  db.prepare('INSERT INTO users(full_name,email,password_hash,role) VALUES(?,?,?,?)').run('Fictional Recovery Administrator', 'recovery.admin@example.test', bcrypt.hashSync(SECOND_ADMIN_PASSWORD, 4), 'ADMIN');
  adminId = db.prepare("SELECT id FROM users WHERE email='primary.admin@example.test'").get().id;
  secondAdminId = db.prepare("SELECT id FROM users WHERE email='recovery.admin@example.test'").get().id;
  studentId = Number(db.prepare('INSERT INTO users(full_name,email,password_hash,role) VALUES(?,?,?,?)').run('Fictional Phase Five Student', 'phase5.student@example.test', bcrypt.hashSync(STUDENT_PASSWORD, 4), 'STUDENT').lastInsertRowid);
  const config = createConfig({ env: { NODE_ENV: 'test', PORT: '0', CLIENT_ORIGIN: 'http://localhost', WEB_DATABASE_PATH: databasePath, AUTH_SECRET: randomBytes(48).toString('hex'), AUTH_EXPIRES_IN: '10m', PUBLIC_REGISTRATION_ROLES: 'STUDENT,TEACHER', ACCOUNT_LOCK_THRESHOLD: '2', ACCOUNT_LOCK_DURATION_MINUTES: '5', RECOVERY_TOKEN_TTL_MINUTES: '5', OPERATIONAL_LOG_ENABLED: 'true' } });
  server = createApp({ db, config, logSink: (line) => logs.push(line) }).listen(0); await new Promise((resolve) => server.once('listening', resolve)); base = `http://127.0.0.1:${server.address().port}`;
  adminToken = (await login('primary.admin@example.test', ADMIN_PASSWORD)).payload.token;
  studentToken = (await login('phase5.student@example.test', STUDENT_PASSWORD)).payload.token;
});
after(async () => { if (server) await new Promise((resolve) => server.close(resolve)); if (db?.open) db.close(); if (dir?.startsWith(os.tmpdir())) fs.rmSync(dir, { recursive: true, force: true }); });

test('Phase 5 migration reaches schema version 4 with lifecycle tables', () => { assert.equal(MIGRATION_VERSION, 4); assert.equal(db.prepare('SELECT MAX(version) version FROM schema_migrations').get().version, 4); for (const table of ['password_recovery_tokens', 'notification_outbox', 'data_lifecycle_runs']) assert.ok(db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name=?").get(table)); });
test('identity administration requires administrator authorization', async () => { assert.equal((await request('/api/admin/users')).response.status, 401); assert.equal((await request('/api/admin/users', { token: studentToken })).response.status, 403); });
test('administrator user listing is paginated and excludes secrets', async () => { const result = await request('/api/admin/users?limit=2', { token: adminToken }); assert.equal(result.response.status, 200); assert.equal(result.payload.data.length, 2); assert.equal('password_hash' in result.payload.data[0], false); assert.equal('auth_version' in result.payload.data[0], false); });
test('final active administrator cannot be demoted or disabled', async () => { assert.equal((await request(`/api/admin/users/${secondAdminId}`, { method: 'PATCH', token: adminToken, body: { status: 'INACTIVE' } })).response.status, 200); const blocked = await request(`/api/admin/users/${adminId}`, { method: 'PATCH', token: adminToken, body: { role: 'STAFF' } }); assert.equal(blocked.response.status, 409); assert.match(blocked.payload.message, /final active administrator/i); assert.equal((await request(`/api/admin/users/${secondAdminId}`, { method: 'PATCH', token: adminToken, body: { status: 'ACTIVE' } })).response.status, 200); });
test('explicit revocation invalidates an already issued JWT', async () => { const result = await request(`/api/admin/users/${studentId}/revoke`, { method: 'POST', token: adminToken }); assert.equal(result.response.status, 200); assert.equal((await request('/api/auth/me', { token: studentToken })).response.status, 401); studentToken = (await login('phase5.student@example.test', STUDENT_PASSWORD)).payload.token; });
test('role changes revoke stale authorization and appear in new tokens', async () => { const old = studentToken; assert.equal((await request(`/api/admin/users/${studentId}`, { method: 'PATCH', token: adminToken, body: { role: 'TEACHER' } })).response.status, 200); assert.equal((await request('/api/auth/me', { token: old })).response.status, 401); const fresh = await login('phase5.student@example.test', STUDENT_PASSWORD); assert.equal(fresh.payload.user.role, 'TEACHER'); studentToken = fresh.payload.token; });
test('failed-login threshold locks the account with generic responses and admin unlock works', async () => { for (let i = 0; i < 2; i += 1) { const result = await login('phase5.student@example.test', 'Wrong!Aa123456789'); assert.equal(result.response.status, 401); assert.equal(result.payload.message, 'Invalid email or password.'); } assert.equal(db.prepare('SELECT security_status FROM users WHERE id=?').get(studentId).security_status, 'LOCKED'); assert.equal((await login('phase5.student@example.test', STUDENT_PASSWORD)).response.status, 401); assert.equal((await request(`/api/admin/users/${studentId}`, { method: 'PATCH', token: adminToken, body: { security_status: 'ACTIVE' } })).response.status, 200); studentToken = (await login('phase5.student@example.test', STUDENT_PASSWORD)).payload.token; });
test('one-time recovery stores only a hash, revokes sessions, and rejects reuse', async () => { const old = studentToken; const initiated = await request(`/api/admin/users/${studentId}/recovery`, { method: 'POST', token: adminToken }); assert.equal(initiated.response.status, 201); const raw = initiated.payload.data.recovery_token; assert.ok(raw.length >= 32); const stored = db.prepare('SELECT token_hash FROM password_recovery_tokens WHERE user_id=? ORDER BY id DESC').get(studentId); assert.notEqual(stored.token_hash, raw); assert.equal((await request('/api/auth/me', { token: old })).response.status, 401); assert.equal((await request('/api/auth/recovery/complete', { method: 'POST', body: { token: raw, password: RECOVERED_PASSWORD } })).response.status, 200); assert.equal((await request('/api/auth/recovery/complete', { method: 'POST', body: { token: raw, password: STUDENT_PASSWORD } })).response.status, 400); studentToken = (await login('phase5.student@example.test', RECOVERED_PASSWORD)).payload.token; });
test('self and administrative exports expose only allowlisted account data', async () => { const own = await request('/api/account/export', { token: studentToken }); const admin = await request(`/api/admin/users/${studentId}/export`, { token: adminToken }); for (const result of [own, admin]) { assert.equal(result.response.status, 200); const serialized = JSON.stringify(result.payload); assert.doesNotMatch(serialized, /password_hash|token_hash|failed_login_count/); } assert.ok(db.prepare("SELECT 1 FROM audit_logs WHERE action='USER_DATA_EXPORT' AND entity_id=?").get(studentId)); });
test('publishing a notification transactionally enqueues one idempotent NOOP job', async () => { const created = await request('/api/notifications', { method: 'POST', token: adminToken, body: { title: 'Synthetic Phase Five Notice', message: 'Synthetic notification only.', notification_type: 'GENERAL', status: 'PUBLISHED' } }); assert.equal(created.response.status, 201); const jobs = db.prepare('SELECT * FROM notification_outbox WHERE notification_id=?').all(created.payload.data.id); assert.equal(jobs.length, 1); outboxJobId=jobs[0].id; assert.equal(jobs[0].channel, 'NOOP'); assert.equal((await request('/api/admin/outbox', { token: studentToken })).response.status, 403); assert.equal((await request('/api/admin/outbox', { token: adminToken })).response.status, 200); });
test('administrator outbox retry and cancellation are bounded and audited', async () => { db.prepare("UPDATE notification_outbox SET status='FAILED',attempt_count=1,last_error_code='SYNTHETIC_FAILURE' WHERE id=?").run(outboxJobId); assert.equal((await request(`/api/admin/outbox/${outboxJobId}/retry`, { method: 'POST', token: adminToken })).payload.data.status, 'PENDING'); assert.equal((await request(`/api/admin/outbox/${outboxJobId}/cancel`, { method: 'POST', token: adminToken })).payload.data.status, 'CANCELLED'); assert.ok(db.prepare("SELECT COUNT(*) count FROM audit_logs WHERE entity_type='NOTIFICATION_OUTBOX' AND entity_id=?").get(outboxJobId).count >= 2); });
test('liveness, readiness, and metrics have separated access boundaries', async () => { assert.equal((await request('/api/health/live')).payload.status, 'ok'); const ready = await request('/api/health/ready'); assert.equal(ready.response.status, 200); assert.equal(ready.payload.schema_version, 4); assert.equal((await request('/api/admin/operations/metrics')).response.status, 401); const metrics = await request('/api/admin/operations/metrics', { token: adminToken }); assert.equal(metrics.response.status, 200); assert.equal(metrics.payload.data.gauges.schema_version, 4); assert.equal(JSON.stringify(metrics.payload).includes('example.test'), false); });
test('structured operational logs correlate requests without credentials or bodies', () => { assert.ok(logs.length > 0); const parsed = JSON.parse(logs.at(-1)); for (const key of ['timestamp', 'severity', 'event', 'request_id', 'route', 'outcome', 'duration_ms', 'environment']) assert.ok(Object.hasOwn(parsed, key)); const all = logs.join('\n'); assert.doesNotMatch(all, /Recovered|Wrong!|Authorization|password|example\.test/i); });
test('identity mutations are audited with redacted metadata', () => { const rows = db.prepare("SELECT metadata_json FROM audit_logs WHERE action IN ('USER_IDENTITY_CHANGE','USER_AUTH_REVOKE','USER_RECOVERY_INITIATE')").all(); assert.ok(rows.length >= 3); assert.doesNotMatch(JSON.stringify(rows), /password|recovery_token|token_hash/i); });
