const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { test } = require('node:test'); const assert = require('node:assert/strict');
const { initializeDatabase } = require('../src/db/connection'); const { createDataGovernanceService } = require('../src/services/dataGovernanceService'); const { createBackup, verifyBackup, createSanitizedExport } = require('../src/db/operations');

test('retention plan reports counts and does not delete records', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'diu-phase5-retention-')); const file = path.join(dir, 'db.sqlite'); const db = initializeDatabase(file); try { db.prepare("INSERT INTO users(full_name,email,password_hash,role) VALUES('Fictional User','retention@example.test','synthetic-hash','STUDENT')").run(); const id = db.prepare('SELECT id FROM users').get().id; db.prepare("INSERT INTO password_recovery_tokens(user_id,token_hash,expires_at,created_at) VALUES(?,?,'2000-01-01','2000-01-01')").run(id, 'a'.repeat(64)); const service = createDataGovernanceService(db); const result = service.plan(); assert.equal(result.mode, 'DRY_RUN'); assert.equal(result.candidate_counts.expired_recovery_tokens, 1); assert.equal(db.prepare('SELECT COUNT(*) count FROM password_recovery_tokens').get().count, 1); } finally { db.close(); fs.rmSync(dir, { recursive: true, force: true }); } });
test('retention apply uses only allowlisted lifecycle records in an isolated database', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'diu-phase5-apply-')); const db = initializeDatabase(path.join(dir, 'db.sqlite')); try { db.prepare("INSERT INTO users(full_name,email,password_hash,role) VALUES('Fictional User','apply@example.test','synthetic-hash','STUDENT')").run(); const id = db.prepare('SELECT id FROM users').get().id; db.prepare("INSERT INTO password_recovery_tokens(user_id,token_hash,expires_at,created_at) VALUES(?,?,'2000-01-01','2000-01-01')").run(id, 'b'.repeat(64)); const result = createDataGovernanceService(db).apply({ backupReference: 'verified-synthetic.db' }); assert.equal(result.deleted_counts.expired_recovery_tokens, 1); assert.equal(db.prepare('SELECT COUNT(*) count FROM password_recovery_tokens').get().count, 0); assert.equal(db.prepare("SELECT outcome FROM data_lifecycle_runs WHERE operation='RETENTION_APPLY'").get().outcome, 'SUCCEEDED'); } finally { db.close(); fs.rmSync(dir, { recursive: true, force: true }); } });
test('anonymization boundary is dry-run and does not mutate identity data', () => { const db = initializeDatabase(':memory:'); try { const id = Number(db.prepare("INSERT INTO users(full_name,email,password_hash,role) VALUES('Fictional User','anon@example.test','synthetic-hash','STUDENT')").run().lastInsertRowid); const result = createDataGovernanceService(db).anonymizationDryRun(id); assert.equal(result.mode, 'DRY_RUN'); assert.equal(db.prepare('SELECT email FROM users WHERE id=?').get(id).email, 'anon@example.test'); } finally { db.close(); } });
test('Phase 5 backup and restore verification includes governance tables', async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'diu-phase5-backup-')); const source = path.join(dir, 'source.db'); const db = initializeDatabase(source); db.close(); try { const backup = await createBackup(source, path.join(dir, 'backups')); const summary = verifyBackup(backup, { sourcePath: source }); assert.equal(summary.schemaVersion, 4); for (const name of ['password_recovery_tokens', 'notification_outbox', 'data_lifecycle_runs']) assert.ok(summary.tables.includes(name)); } finally { fs.rmSync(dir, { recursive: true, force: true }); } });
test('sanitized export excludes password and recovery hash values', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'diu-phase5-export-')); const source = path.join(dir, 'source.db'); const db = initializeDatabase(source); db.close(); try { const result = createSanitizedExport(source, path.join(dir, 'exports')); const payload = JSON.parse(fs.readFileSync(result.destination, 'utf8')); assert.equal(payload.data.users.some((row) => 'password_hash' in row), false); assert.equal(payload.data.password_recovery_tokens.some((row) => 'token_hash' in row), false); assert.ok(Object.hasOwn(payload.data, 'notification_outbox')); } finally { fs.rmSync(dir, { recursive: true, force: true }); } });
