const { AppError } = require('../middleware/errors');
const { validateFeedbackInput, validateFeedbackAdminInput } = require('../utils/validation');

const TRANSITIONS={NEW:new Set(['IN_REVIEW','CLOSED']),IN_REVIEW:new Set(['RESOLVED','CLOSED']),RESOLVED:new Set(['CLOSED']),CLOSED:new Set()};

function createFeedbackService(db,auditService,{pageSizeMax=100}={}){
  const select=`SELECT f.*,u.full_name AS submitter_name,e.employee_code AS assigned_employee_code,e.full_name AS assigned_employee_name FROM feedback f JOIN users u ON u.id=f.submitted_by LEFT JOIN employees e ON e.id=f.assigned_to`;
  const find=db.prepare(`${select} WHERE f.id=?`);
  function submit(payload,userId){const result=validateFeedbackInput(payload);if(!result.valid)throw new AppError(400,result.errors[0],result.errors);const info=db.prepare('INSERT INTO feedback(submitted_by,category,subject,message) VALUES(?,?,?,?)').run(userId,result.value.category,result.value.subject,result.value.message);return find.get(info.lastInsertRowid);}
  function mine(userId){return db.prepare(`${select} WHERE f.submitted_by=? ORDER BY f.created_at DESC,f.id DESC`).all(userId);}
  function getMine(id,userId){const row=find.get(id);if(!row||row.submitted_by!==userId)throw new AppError(404,'Feedback not found.');return row;}
  function adminList(query={}){const page=Number.parseInt(query.page||'1',10),limit=Number.parseInt(query.limit||'25',10);if(!Number.isInteger(page)||page<1)throw new AppError(400,'Page must be a positive integer.');if(!Number.isInteger(limit)||limit<1||limit>pageSizeMax)throw new AppError(400,`Limit must be between 1 and ${pageSizeMax}.`);const clauses=[],params={};if(query.status){params.status=String(query.status).toUpperCase();clauses.push('f.status=@status');}if(query.category){params.category=String(query.category).toUpperCase();clauses.push('f.category=@category');}if(query.assigned_to){params.assigned_to=Number(query.assigned_to);if(!Number.isInteger(params.assigned_to)||params.assigned_to<=0)throw new AppError(400,'Assigned employee filter is invalid.');clauses.push('f.assigned_to=@assigned_to');}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=db.prepare(`SELECT COUNT(*) count FROM feedback f ${where}`).get(params).count;const data=db.prepare(`${select} ${where} ORDER BY f.created_at DESC,f.id DESC LIMIT @limit OFFSET @offset`).all({...params,limit,offset:(page-1)*limit});return{data,pagination:{page,limit,total,total_pages:Math.max(1,Math.ceil(total/limit))}};}
  function adminGet(id){const row=find.get(id);if(!row)throw new AppError(404,'Feedback not found.');return row;}
  function update(id,payload,context){const existing=adminGet(id),result=validateFeedbackAdminInput(payload);if(!result.valid)throw new AppError(400,result.errors[0],result.errors);const value=result.value;if(value.status&&value.status!==existing.status&&!TRANSITIONS[existing.status].has(value.status))throw new AppError(409,`Feedback cannot transition from ${existing.status} to ${value.status}.`);if(value.assigned_to){const employee=db.prepare("SELECT id FROM employees WHERE id=? AND status='ACTIVE'").get(value.assigned_to);if(!employee)throw new AppError(400,'Assigned employee must exist and be active.');}const next={status:value.status??existing.status,admin_response:value.admin_response===undefined?existing.admin_response:value.admin_response,assigned_to:value.assigned_to===undefined?existing.assigned_to:value.assigned_to};const resolvedAt=next.status==='RESOLVED'?(existing.resolved_at||new Date().toISOString()):next.status==='CLOSED'?existing.resolved_at:null;return db.transaction(()=>{db.prepare('UPDATE feedback SET status=?,admin_response=?,assigned_to=?,resolved_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(next.status,next.admin_response,next.assigned_to,resolvedAt,id);auditService.record({actorUserId:context.actorUserId,action:'FEEDBACK_ADMIN_UPDATE',entityType:'FEEDBACK',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{changed_fields:Object.keys(payload),previous_status:existing.status,new_status:next.status}});return adminGet(id);})();}
  return{submit,mine,getMine,adminList,adminGet,update};
}
module.exports={createFeedbackService,TRANSITIONS};
