const { AppError } = require('../middleware/errors');
const { validateNotificationInput, validateFields } = require('../utils/validation');

const NOTIFICATION_FIELDS=new Set(['title','message','notification_type','audience_role','related_entity_type','related_entity_id','status','publish_at','expires_at']);
const RELATED_TABLES={SCHEDULE:'schedules',SPECIAL_TRIP:'special_trips',ROUTE:'routes',EMERGENCY_CONTACT:'emergency_contacts',FEEDBACK:'feedback'};

function createNotificationService(db,auditService,{pageSizeMax=100}={}){
  const find=db.prepare('SELECT * FROM notifications WHERE id=?');
  function validate(payload){const result=validateNotificationInput(payload);if(!result.valid)throw new AppError(400,result.errors[0],result.errors);if(result.value.related_entity_type){const table=RELATED_TABLES[result.value.related_entity_type];if(!table)throw new AppError(400,'Related entity type is invalid.');if(!db.prepare(`SELECT id FROM ${table} WHERE id=?`).get(result.value.related_entity_id))throw new AppError(400,'Related entity does not exist.');}return result.value;}
  function visibleClause(){return `n.status='PUBLISHED' AND (n.publish_at IS NULL OR datetime(n.publish_at)<=CURRENT_TIMESTAMP) AND (n.expires_at IS NULL OR datetime(n.expires_at)>CURRENT_TIMESTAMP) AND (n.audience_role IS NULL OR n.audience_role=@role)`;}
  function listForUser(user){const rows=db.prepare(`SELECT n.*,CASE WHEN nr.user_id IS NULL THEN 0 ELSE 1 END AS is_read FROM notifications n LEFT JOIN notification_reads nr ON nr.notification_id=n.id AND nr.user_id=@user_id WHERE ${visibleClause()} ORDER BY COALESCE(n.publish_at,n.created_at) DESC,n.id DESC`).all({user_id:user.id,role:user.role});return{data:rows,unread_count:rows.filter((row)=>!row.is_read).length};}
  function getForUser(id,user){const row=db.prepare(`SELECT n.*,CASE WHEN nr.user_id IS NULL THEN 0 ELSE 1 END AS is_read FROM notifications n LEFT JOIN notification_reads nr ON nr.notification_id=n.id AND nr.user_id=@user_id WHERE n.id=@id AND ${visibleClause()}`).get({id,user_id:user.id,role:user.role});if(!row)throw new AppError(404,'Notification not found.');return row;}
  function adminList(query={}){const page=Number.parseInt(query.page||'1',10),limit=Number.parseInt(query.limit||'25',10);if(!Number.isInteger(page)||page<1)throw new AppError(400,'Page must be a positive integer.');if(!Number.isInteger(limit)||limit<1||limit>pageSizeMax)throw new AppError(400,`Limit must be between 1 and ${pageSizeMax}.`);const clauses=[],params={};for(const [key,column] of [['status','status'],['notification_type','notification_type'],['audience_role','audience_role']]){if(query[key]){params[key]=String(query[key]).toUpperCase();clauses.push(`${column}=@${key}`);}}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=db.prepare(`SELECT COUNT(*) count FROM notifications ${where}`).get(params).count;const data=db.prepare(`SELECT * FROM notifications ${where} ORDER BY created_at DESC,id DESC LIMIT @limit OFFSET @offset`).all({...params,limit,offset:(page-1)*limit});return{data,pagination:{page,limit,total,total_pages:Math.max(1,Math.ceil(total/limit))}};}
  function adminGet(id){const row=find.get(id);if(!row)throw new AppError(404,'Notification not found.');return row;}
  function create(payload,context){const value=validate(payload);if(value.status==='EXPIRED'||value.status==='CANCELLED')throw new AppError(400,'New notifications must be DRAFT or PUBLISHED.');if(value.status==='PUBLISHED'&&!value.publish_at)value.publish_at=new Date().toISOString();return db.transaction(()=>{const info=db.prepare(`INSERT INTO notifications(title,message,notification_type,audience_role,related_entity_type,related_entity_id,status,publish_at,expires_at,created_by)
    VALUES(@title,@message,@notification_type,@audience_role,@related_entity_type,@related_entity_id,@status,@publish_at,@expires_at,@created_by)`).run({...value,created_by:context.actorUserId});const id=Number(info.lastInsertRowid);auditService.record({actorUserId:context.actorUserId,action:'NOTIFICATION_CREATE',entityType:'NOTIFICATION',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{changed_fields:Object.keys(value),new_status:value.status}});return adminGet(id);})();}
  function update(id,payload,context){const existing=adminGet(id);if(existing.status!=='DRAFT')throw new AppError(409,'Only draft notifications can be edited.');const fieldErrors=validateFields(payload,NOTIFICATION_FIELDS);if(fieldErrors.length)throw new AppError(400,fieldErrors[0],fieldErrors);const candidate=Object.fromEntries([...NOTIFICATION_FIELDS].map((field)=>[field,Object.prototype.hasOwnProperty.call(payload,field)?payload[field]:existing[field]]));const value=validate(candidate);if(value.status!=='DRAFT')throw new AppError(400,'Use the publish or cancel action to change notification status.');return db.transaction(()=>{db.prepare(`UPDATE notifications SET title=@title,message=@message,notification_type=@notification_type,audience_role=@audience_role,related_entity_type=@related_entity_type,related_entity_id=@related_entity_id,publish_at=@publish_at,expires_at=@expires_at,updated_at=CURRENT_TIMESTAMP WHERE id=@id`).run({...value,id});auditService.record({actorUserId:context.actorUserId,action:'NOTIFICATION_UPDATE',entityType:'NOTIFICATION',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{changed_fields:Object.keys(payload)}});return adminGet(id);})();}
  function transition(id,target,context){const existing=adminGet(id);const allowed={PUBLISHED:new Set(['DRAFT']),CANCELLED:new Set(['DRAFT','PUBLISHED']),EXPIRED:new Set(['PUBLISHED'])};if(!allowed[target]?.has(existing.status))throw new AppError(409,`Notification cannot transition from ${existing.status} to ${target}.`);return db.transaction(()=>{const publishAt=target==='PUBLISHED'?(existing.publish_at||new Date().toISOString()):existing.publish_at;db.prepare('UPDATE notifications SET status=?,publish_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(target,publishAt,id);auditService.record({actorUserId:context.actorUserId,action:`NOTIFICATION_${target==='PUBLISHED'?'PUBLISH':target}`,entityType:'NOTIFICATION',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{previous_status:existing.status,new_status:target}});return adminGet(id);})();}
  function markRead(id,user){getForUser(id,user);db.prepare('INSERT INTO notification_reads(notification_id,user_id) VALUES(?,?) ON CONFLICT(notification_id,user_id) DO UPDATE SET read_at=excluded.read_at').run(id,user.id);return getForUser(id,user);}
  function createAutomatic({title,message,notificationType,audienceRole=null,relatedEntityType,relatedEntityId,dedupeKey,createdBy,requestId}){const validation=validateNotificationInput({title,message,notification_type:notificationType,audience_role:audienceRole,related_entity_type:relatedEntityType,related_entity_id:relatedEntityId,status:'PUBLISHED',publish_at:new Date().toISOString()});if(!validation.valid)throw new Error(validation.errors[0]);const value=validation.value;const info=db.prepare(`INSERT OR IGNORE INTO notifications(title,message,notification_type,audience_role,related_entity_type,related_entity_id,status,publish_at,created_by,dedupe_key)
    VALUES(@title,@message,@notification_type,@audience_role,@related_entity_type,@related_entity_id,'PUBLISHED',@publish_at,@created_by,@dedupe_key)`).run({...value,created_by:createdBy,dedupe_key:String(dedupeKey).slice(0,200)});if(info.changes){const id=Number(info.lastInsertRowid);auditService.record({actorUserId:createdBy,action:'NOTIFICATION_AUTO_CREATE',entityType:'NOTIFICATION',entityId:id,outcome:'SUCCESS',requestId,metadata:{source:'automatic_event',new_status:'PUBLISHED'}});return adminGet(id);}return db.prepare('SELECT * FROM notifications WHERE dedupe_key=?').get(String(dedupeKey).slice(0,200));}
  return{listForUser,getForUser,adminList,adminGet,create,update,publish:(id,c)=>transition(id,'PUBLISHED',c),cancel:(id,c)=>transition(id,'CANCELLED',c),expire:(id,c)=>transition(id,'EXPIRED',c),markRead,createAutomatic};
}
module.exports={createNotificationService,RELATED_TABLES};
