const { AppError } = require('../middleware/errors');
const { validateSpecialTripInput, validateFields } = require('../utils/validation');

const SPECIAL_FIELDS=new Set(['category','title','description','organizer']);
const CREATE_FIELDS=new Set([...SPECIAL_FIELDS,'schedule']);
const UPDATE_FIELDS=new Set([...SPECIAL_FIELDS,'schedule']);
const SELECT=`SELECT st.*,s.route_id,s.bus_id,s.driver_id,s.service_date,s.departure_time,s.arrival_time,s.trip_type,s.status AS schedule_status,s.notes,
 r.route_name,r.origin,r.destination,b.bus_number,d.full_name AS driver_name
 FROM special_trips st JOIN schedules s ON s.id=st.schedule_id JOIN routes r ON r.id=s.route_id JOIN buses b ON b.id=s.bus_id JOIN drivers d ON d.id=s.driver_id`;

function createSpecialTripService(db,auditService,scheduleService,notificationService,{pageSizeMax=100}={}){
  const find=db.prepare(`${SELECT} WHERE st.id=?`);
  function map(row,isAdmin=true){const result={id:row.id,category:row.category,title:row.title,description:row.description,organizer:row.organizer,approval_status:row.approval_status,created_at:row.created_at,updated_at:row.updated_at,schedule:{id:row.schedule_id,service_date:row.service_date,departure_time:row.departure_time,arrival_time:row.arrival_time,status:row.schedule_status,notes:row.notes,route:{id:row.route_id,name:row.route_name,origin:row.origin,destination:row.destination},bus:{id:row.bus_id,number:row.bus_number},driver:{id:row.driver_id,name:row.driver_name}}};if(isAdmin)Object.assign(result,{requested_by:row.requested_by,approved_by:row.approved_by,approved_at:row.approved_at});return result;}
  function adminGet(id){const row=find.get(id);if(!row)throw new AppError(404,'Special trip not found.');return map(row,true);}
  function getForUser(id){const row=find.get(id);if(!row||row.approval_status!=='APPROVED')throw new AppError(404,'Special trip not found.');return map(row,false);}
  function list({isAdmin=false,page=1,limit=25}={}){page=Number(page);limit=Number(limit);if(!Number.isInteger(page)||page<1)throw new AppError(400,'Page must be a positive integer.');if(!Number.isInteger(limit)||limit<1||limit>pageSizeMax)throw new AppError(400,`Limit must be between 1 and ${pageSizeMax}.`);const where=isAdmin?'':"WHERE st.approval_status='APPROVED'";const total=db.prepare(`SELECT COUNT(*) count FROM special_trips st ${where}`).get().count;const data=db.prepare(`${SELECT} ${where} ORDER BY s.service_date,s.departure_time,st.id LIMIT ? OFFSET ?`).all(limit,(page-1)*limit).map((row)=>map(row,isAdmin));return{data,pagination:{page,limit,total,total_pages:Math.max(1,Math.ceil(total/limit))}};}
  function validateDetails(payload){const sanitized=Object.fromEntries([...SPECIAL_FIELDS].map((field)=>[field,payload[field]]));const result=validateSpecialTripInput({...sanitized,approval_status:'DRAFT'});if(!result.valid)throw new AppError(400,result.errors[0],result.errors);return result.value;}
  function create(payload,context){const fieldErrors=validateFields(payload,CREATE_FIELDS);if(fieldErrors.length)throw new AppError(400,fieldErrors[0],fieldErrors);if(!payload.schedule||typeof payload.schedule!=='object')throw new AppError(400,'Special-trip schedule is required.');const details=validateDetails(payload);return db.transaction(()=>{const schedule=scheduleService.create({...payload.schedule,trip_type:'SPECIAL',status:'CANCELLED'},context.actorUserId,{...context,suppressAutomaticNotification:true});const info=db.prepare(`INSERT INTO special_trips(schedule_id,category,title,description,organizer,requested_by) VALUES(?,?,?,?,?,?)`).run(schedule.id,details.category,details.title,details.description,details.organizer,context.actorUserId);const id=Number(info.lastInsertRowid);auditService.record({actorUserId:context.actorUserId,action:'SPECIAL_TRIP_CREATE',entityType:'SPECIAL_TRIP',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{changed_fields:['category','title','description','organizer','schedule'],new_status:'DRAFT'}});return adminGet(id);})();}
  function update(id,payload,context){const existing=adminGet(id);if(existing.approval_status!=='DRAFT')throw new AppError(409,'Only draft special trips can be edited.');const fieldErrors=validateFields(payload,UPDATE_FIELDS);if(fieldErrors.length)throw new AppError(400,fieldErrors[0],fieldErrors);const candidate=Object.fromEntries([...SPECIAL_FIELDS].map((field)=>[field,Object.prototype.hasOwnProperty.call(payload,field)?payload[field]:existing[field]]));const details=validateDetails(candidate);return db.transaction(()=>{if(payload.schedule){if(typeof payload.schedule!=='object')throw new AppError(400,'Schedule changes must be an object.');scheduleService.update(existing.schedule.id,{...payload.schedule,trip_type:'SPECIAL',status:'CANCELLED'},context.actorUserId,{...context,suppressAutomaticNotification:true});}db.prepare('UPDATE special_trips SET category=?,title=?,description=?,organizer=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(details.category,details.title,details.description,details.organizer,id);auditService.record({actorUserId:context.actorUserId,action:'SPECIAL_TRIP_UPDATE',entityType:'SPECIAL_TRIP',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{changed_fields:Object.keys(payload)}});return adminGet(id);})();}
  function approve(id,context){const operation=db.transaction(()=>{const existing=adminGet(id);if(existing.approval_status!=='DRAFT')throw new AppError(409,`Special trip cannot transition from ${existing.approval_status} to APPROVED.`);scheduleService.update(existing.schedule.id,{status:'ACTIVE'},context.actorUserId,{...context,suppressAutomaticNotification:true});db.prepare("UPDATE special_trips SET approval_status='APPROVED',approved_by=?,approved_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(context.actorUserId,id);notificationService.createAutomatic({title:'Special trip approved',message:`${existing.title} is approved for ${existing.schedule.service_date}.`,notificationType:'SPECIAL_TRIP',relatedEntityType:'SPECIAL_TRIP',relatedEntityId:id,dedupeKey:`special-trip:${id}:approved`,createdBy:context.actorUserId,requestId:context.requestId});auditService.record({actorUserId:context.actorUserId,action:'SPECIAL_TRIP_APPROVE',entityType:'SPECIAL_TRIP',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{previous_status:'DRAFT',new_status:'APPROVED'}});return adminGet(id);});try{return operation();}catch(error){if(error.statusCode===409)auditService.record({actorUserId:context.actorUserId,action:'SPECIAL_TRIP_APPROVE',entityType:'SPECIAL_TRIP',entityId:id,outcome:'CONFLICT',requestId:context.requestId,metadata:{reason:/bus/i.test(error.message)?'bus_conflict':/driver/i.test(error.message)?'driver_conflict':'invalid_transition'}});throw error;}}
  function cancel(id,context){return db.transaction(()=>{const existing=adminGet(id);if(!['DRAFT','APPROVED'].includes(existing.approval_status))throw new AppError(409,`Special trip cannot transition from ${existing.approval_status} to CANCELLED.`);scheduleService.deactivate(existing.schedule.id,context.actorUserId,{...context,suppressAutomaticNotification:true});db.prepare("UPDATE special_trips SET approval_status='CANCELLED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);notificationService.createAutomatic({title:'Special trip cancelled',message:`${existing.title} has been cancelled.`,notificationType:'SPECIAL_TRIP',relatedEntityType:'SPECIAL_TRIP',relatedEntityId:id,dedupeKey:`special-trip:${id}:cancelled`,createdBy:context.actorUserId,requestId:context.requestId});auditService.record({actorUserId:context.actorUserId,action:'SPECIAL_TRIP_CANCEL',entityType:'SPECIAL_TRIP',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{previous_status:existing.approval_status,new_status:'CANCELLED'}});return adminGet(id);})();}
  function complete(id,context){return db.transaction(()=>{const existing=adminGet(id);if(existing.approval_status!=='APPROVED')throw new AppError(409,`Special trip cannot transition from ${existing.approval_status} to COMPLETED.`);db.prepare("UPDATE special_trips SET approval_status='COMPLETED',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);auditService.record({actorUserId:context.actorUserId,action:'SPECIAL_TRIP_COMPLETE',entityType:'SPECIAL_TRIP',entityId:id,outcome:'SUCCESS',requestId:context.requestId,metadata:{previous_status:'APPROVED',new_status:'COMPLETED'}});return adminGet(id);})();}
  return{list,getForUser,adminGet,create,update,approve,cancel,complete};
}
module.exports={createSpecialTripService};
