(() => {
  'use strict';
  const app=window.diuApp;const byId=(id)=>document.getElementById(id);const esc=app.escapeHtml;const resources={employees:[],contacts:[],trips:[],notifications:[],feedback:[]};
  const isAdmin=()=>app.getUser()?.role==='ADMIN';const message=(id,text='')=>{byId(id).textContent=text;};
  const beginList=(id,label)=>{const list=byId(id);list.setAttribute('aria-busy','true');list.innerHTML=`<p class="loading-state">Loading ${esc(label)}…</p>`;return list;};
  const finishList=(list,items,label)=>{list.removeAttribute('aria-busy');if(!items.length)list.innerHTML=`<p class="empty-state">No ${esc(label)} are available.</p>`;};
  async function load(view){try{if(view==='employees')await loadEmployees();if(view==='special-trips')await loadTrips();if(view==='notifications')await loadNotifications();if(view==='contacts')await loadContacts();if(view==='feedback')await loadFeedback();}catch(error){app.showWorkspaceMessage(error.message,true);}}
  function catalogOptions(){const catalog=app.getCatalog()||{routes:[],buses:[],drivers:[]};for(const[id,items,label]of[['special-route',catalog.routes,(x)=>x.route_name],['special-bus',catalog.buses,(x)=>x.bus_number],['special-driver',catalog.drivers,(x)=>x.full_name]]){const select=byId(id);select.replaceChildren(new Option('Select…',''));items.forEach((item)=>select.add(new Option(label(item),item.id)));}}

  async function loadEmployees(){if(!isAdmin())return;const list=beginList('employee-list','employees');resources.employees=(await app.api('/api/employees')).data;list.replaceChildren();for(const item of resources.employees){const card=document.createElement('article');card.className='record-card';card.innerHTML=`<div><h3>${esc(item.full_name)}</h3><p>${esc(item.employee_code)} · ${esc(item.employee_role)} · ${esc(item.shift)}</p><p>${esc(item.phone)}${item.email?` · ${esc(item.email)}`:''}</p></div><span class="status-text ${item.status}">${esc(item.status)}</span><div class="row-actions"><button class="button button-quiet" data-employee="edit" data-id="${item.id}" type="button">Edit</button><button class="button ${item.status==='ACTIVE'?'button-danger':'button-secondary'}" data-employee="${item.status==='ACTIVE'?'deactivate':'reactivate'}" data-id="${item.id}" type="button">${item.status==='ACTIVE'?'Deactivate':'Reactivate'}</button></div>`;list.append(card);}finishList(list,resources.employees,'employees');}
  function resetEmployee(){byId('employee-form').reset();byId('employee-id').value='';byId('employee-cancel').hidden=true;message('employee-message');}
  function editEmployee(id){const item=resources.employees.find((x)=>x.id===id);if(!item)return;for(const[key,value]of[['employee-id',item.id],['employee-code',item.employee_code],['employee-name',item.full_name],['employee-role',item.employee_role],['employee-phone',item.phone],['employee-email',item.email||''],['employee-shift',item.shift],['employee-notes',item.notes||'']])byId(key).value=value;byId('employee-cancel').hidden=false;}
  async function submitEmployee(){const id=byId('employee-id').value;const body={employee_code:byId('employee-code').value,full_name:byId('employee-name').value,employee_role:byId('employee-role').value,phone:byId('employee-phone').value,email:byId('employee-email').value||null,shift:byId('employee-shift').value,notes:byId('employee-notes').value||null};await app.api(id?`/api/employees/${id}`:'/api/employees',{method:id?'PATCH':'POST',body:JSON.stringify(body)});resetEmployee();await loadEmployees();}

  async function loadTrips(){byId('special-trip-form').hidden=!isAdmin();catalogOptions();const list=beginList('special-trip-list','special trips');resources.trips=(await app.api('/api/special-trips?limit=100')).data;list.replaceChildren();for(const item of resources.trips){const actions=isAdmin()?`<div class="row-actions">${item.approval_status==='DRAFT'?`<button class="button button-primary" data-trip="approve" data-id="${item.id}" type="button">Approve</button>`:''}${['DRAFT','APPROVED'].includes(item.approval_status)?`<button class="button button-danger" data-trip="cancel" data-id="${item.id}" type="button">Cancel</button>`:''}${item.approval_status==='APPROVED'?`<button class="button button-secondary" data-trip="complete" data-id="${item.id}" type="button">Complete</button>`:''}</div>`:'';const card=document.createElement('article');card.className='record-card';card.innerHTML=`<div><p class="eyebrow">${esc(item.category)}</p><h3>${esc(item.title)}</h3><p>${esc(item.schedule.route.name)} · ${esc(item.schedule.service_date)} · ${esc(item.schedule.departure_time)}–${esc(item.schedule.arrival_time)}</p><p>Bus ${esc(item.schedule.bus.number)} · Driver ${esc(item.schedule.driver.name)} · Organizer ${esc(item.organizer)}</p></div><span class="status-text ${item.approval_status}">${esc(item.approval_status)}</span>${actions}`;list.append(card);}finishList(list,resources.trips,'special trips');}
  async function submitTrip(){const body={category:byId('special-category').value,title:byId('special-title').value,description:byId('special-description').value||null,organizer:byId('special-organizer').value,schedule:{route_id:Number(byId('special-route').value),bus_id:Number(byId('special-bus').value),driver_id:Number(byId('special-driver').value),service_date:byId('special-date').value,departure_time:byId('special-departure').value,arrival_time:byId('special-arrival').value,notes:'Special trip managed in the operations workspace.'}};await app.api('/api/special-trips',{method:'POST',body:JSON.stringify(body)});byId('special-trip-form').reset();catalogOptions();await loadTrips();}

  async function loadNotifications(){byId('notification-form').hidden=!isAdmin();const list=beginList('notification-list','notifications');const payload=await app.api(isAdmin()?'/api/notifications?view=all&limit=100':'/api/notifications');resources.notifications=payload.data;byId('notification-unread').textContent=`${payload.unread_count||0} unread`;list.replaceChildren();for(const item of resources.notifications){let actions='';if(isAdmin()){actions=`<div class="row-actions">${item.status==='DRAFT'?`<button class="button button-primary" data-notification="publish" data-id="${item.id}" type="button">Publish</button>`:''}${['DRAFT','PUBLISHED'].includes(item.status)?`<button class="button button-danger" data-notification="cancel" data-id="${item.id}" type="button">Cancel</button>`:''}${item.status==='PUBLISHED'?`<button class="button button-secondary" data-notification="expire" data-id="${item.id}" type="button">Expire</button>`:''}</div>`;}else if(!item.is_read)actions=`<div class="row-actions"><button class="button button-secondary" data-notification="read" data-id="${item.id}" type="button">Mark read</button></div>`;const card=document.createElement('article');card.className=`record-card${item.is_read?' is-read':''}`;card.innerHTML=`<div><p class="eyebrow">${esc(item.notification_type)}</p><h3>${esc(item.title)}</h3><p>${esc(item.message)}</p><small>${item.audience_role?`Audience: ${esc(item.audience_role)}`:'All authenticated users'}</small></div><span class="status-text ${item.status}">${esc(item.status)}</span>${actions}`;list.append(card);}finishList(list,resources.notifications,'notifications');}
  async function submitNotification(){await app.api('/api/notifications',{method:'POST',body:JSON.stringify({title:byId('notification-title').value,message:byId('notification-message').value,notification_type:byId('notification-type').value,audience_role:byId('notification-audience').value||null,status:'DRAFT'})});byId('notification-form').reset();await loadNotifications();}

  async function loadContacts(){byId('contact-form').hidden=!isAdmin();const list=beginList('contact-list','emergency contacts');resources.contacts=(await app.api('/api/contacts')).data;list.replaceChildren();for(const item of resources.contacts){const actions=isAdmin()?`<div class="row-actions"><button class="button ${item.status==='ACTIVE'?'button-danger':'button-secondary'}" data-contact="${item.status==='ACTIVE'?'deactivate':'reactivate'}" data-id="${item.id}" type="button">${item.status==='ACTIVE'?'Deactivate':'Reactivate'}</button></div>`:'';const card=document.createElement('article');card.className='record-card';card.innerHTML=`<div><h3>${esc(item.contact_name)}</h3><p>${esc(item.contact_role)} · ${esc(item.availability)}</p><p><a href="tel:${esc(item.phone)}">${esc(item.phone)}</a>${item.email?` · <a href="mailto:${esc(item.email)}">${esc(item.email)}</a>`:''}</p></div>${item.status?`<span class="status-text ${item.status}">${esc(item.status)}</span>`:''}${actions}`;list.append(card);}finishList(list,resources.contacts,'emergency contacts');}
  async function submitContact(){await app.api('/api/contacts',{method:'POST',body:JSON.stringify({contact_name:byId('contact-name').value,contact_role:byId('contact-role').value,phone:byId('contact-phone').value,email:byId('contact-email').value||null,availability:byId('contact-availability').value,display_order:Number(byId('contact-order').value)})});byId('contact-form').reset();byId('contact-order').value='0';await loadContacts();}

  async function loadFeedback(){const admin=isAdmin();byId('feedback-form').hidden=admin;const list=beginList('feedback-list','feedback records');const payload=await app.api(admin?'/api/admin/feedback?limit=100':'/api/feedback/mine');resources.feedback=payload.data;list.replaceChildren();for(const item of resources.feedback){const actions=admin&&item.status==='NEW'?`<div class="row-actions"><button class="button button-secondary" data-feedback="review" data-id="${item.id}" type="button">Start review</button></div>`:admin&&item.status==='IN_REVIEW'?`<div class="row-actions"><button class="button button-primary" data-feedback="resolve" data-id="${item.id}" type="button">Resolve</button></div>`:'';const card=document.createElement('article');card.className='record-card';card.innerHTML=`<div><p class="eyebrow">${esc(item.category)}</p><h3>${esc(item.subject)}</h3><p>${esc(item.message)}</p>${item.admin_response?`<p><strong>Administrator response:</strong> ${esc(item.admin_response)}</p>`:''}</div><span class="status-text ${item.status}">${esc(item.status)}</span>${actions}`;list.append(card);}finishList(list,resources.feedback,'feedback records');}
  async function submitFeedback(){await app.api('/api/feedback',{method:'POST',body:JSON.stringify({category:byId('feedback-category').value,subject:byId('feedback-subject').value,message:byId('feedback-message-input').value})});byId('feedback-form').reset();message('feedback-message','Feedback submitted.');await loadFeedback();}

  byId('employee-form').addEventListener('submit',async(e)=>{e.preventDefault();try{await submitEmployee();}catch(error){message('employee-message',error.message);}});byId('employee-cancel').addEventListener('click',resetEmployee);byId('employee-list').addEventListener('click',async(e)=>{const button=e.target.closest('[data-employee]');if(!button)return;if(button.dataset.employee==='edit')return editEmployee(Number(button.dataset.id));if(button.dataset.employee==='deactivate'&&!window.confirm('Deactivate this employee? The historical record will be preserved.'))return;try{await app.api(button.dataset.employee==='deactivate'?`/api/employees/${button.dataset.id}`:`/api/employees/${button.dataset.id}/reactivate`,{method:button.dataset.employee==='deactivate'?'DELETE':'POST'});await loadEmployees();}catch(error){app.showWorkspaceMessage(error.message,true);}});
  byId('special-trip-form').addEventListener('submit',async(e)=>{e.preventDefault();try{await submitTrip();}catch(error){message('special-message',error.message);}});byId('special-trip-list').addEventListener('click',async(e)=>{const button=e.target.closest('[data-trip]');if(!button)return;if(button.dataset.trip==='cancel'&&!window.confirm('Cancel this special trip? The operational record will be preserved.'))return;try{await app.api(`/api/special-trips/${button.dataset.id}/${button.dataset.trip}`,{method:'POST'});await loadTrips();}catch(error){app.showWorkspaceMessage(error.message,true);}});
  byId('notification-form').addEventListener('submit',async(e)=>{e.preventDefault();try{await submitNotification();}catch(error){message('notification-message-status',error.message);}});byId('notification-list').addEventListener('click',async(e)=>{const button=e.target.closest('[data-notification]');if(!button)return;if(['cancel','expire'].includes(button.dataset.notification)&&!window.confirm(`${button.dataset.notification==='cancel'?'Cancel':'Expire'} this notification?`))return;try{await app.api(`/api/notifications/${button.dataset.id}/${button.dataset.notification}`,{method:'POST'});await loadNotifications();}catch(error){app.showWorkspaceMessage(error.message,true);}});
  byId('contact-form').addEventListener('submit',async(e)=>{e.preventDefault();try{await submitContact();}catch(error){message('contact-message',error.message);}});byId('contact-list').addEventListener('click',async(e)=>{const button=e.target.closest('[data-contact]');if(!button)return;if(button.dataset.contact==='deactivate'&&!window.confirm('Deactivate this emergency contact?'))return;try{await app.api(button.dataset.contact==='deactivate'?`/api/contacts/${button.dataset.id}`:`/api/contacts/${button.dataset.id}/reactivate`,{method:button.dataset.contact==='deactivate'?'DELETE':'POST'});await loadContacts();}catch(error){app.showWorkspaceMessage(error.message,true);}});
  byId('feedback-form').addEventListener('submit',async(e)=>{e.preventDefault();try{await submitFeedback();}catch(error){message('feedback-message',error.message);}});byId('feedback-list').addEventListener('click',async(e)=>{const button=e.target.closest('[data-feedback]');if(!button)return;const response=window.prompt(button.dataset.feedback==='resolve'?'Resolution response:':'Optional review response:','Synthetic administrator response.');if(response===null)return;try{await app.api(`/api/admin/feedback/${button.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:button.dataset.feedback==='resolve'?'RESOLVED':'IN_REVIEW',admin_response:response})});await loadFeedback();}catch(error){app.showWorkspaceMessage(error.message,true);}});
  window.diuPhase4={load};
})();
