(() => {
  'use strict';
  const app = window.diuApp; const byId = (id) => document.getElementById(id); const esc = app.escapeHtml;
  let recoveryTrigger = null;
  async function load(view) { if (view === 'users') await loadUsers(); if (view === 'outbox') await loadOutbox(); if (view === 'operations') await loadOperations(); }
  async function loadUsers() {
    const list = byId('user-admin-list'); list.setAttribute('aria-busy', 'true');
    try { const users = (await app.api('/api/admin/users?limit=100')).data; list.replaceChildren(); for (const user of users) { const card = document.createElement('article'); card.className = 'record-card'; const roles=['STUDENT','TEACHER','STAFF','ADMIN'].map((role)=>`<option${role===user.role?' selected':''}>${role}</option>`).join(''); card.innerHTML = `<div><h3>${esc(user.full_name)}</h3><p>${esc(user.email)}</p><p>Account: ${esc(user.status)} · Security: ${esc(user.security_status)}</p><label for="user-role-${user.id}">Role</label> <select id="user-role-${user.id}" data-user-role="${user.id}">${roles}</select></div><div class="row-actions"><button class="button button-secondary" data-user-action="role" data-id="${user.id}" type="button">Save role</button><button class="button button-secondary" data-user-action="toggle" data-id="${user.id}" data-status="${user.status}" type="button">${user.status === 'ACTIVE' ? 'Deactivate' : 'Reactivate'}</button><button class="button button-secondary" data-user-action="security" data-id="${user.id}" data-security="${user.security_status}" type="button">${user.security_status === 'ACTIVE' ? 'Lock' : 'Unlock'}</button><button class="button button-quiet" data-user-action="revoke" data-id="${user.id}" type="button">Revoke sessions</button><button class="button button-primary" data-user-action="recover" data-id="${user.id}" type="button">Start recovery</button></div>`; list.append(card); } } finally { list.removeAttribute('aria-busy'); }
  }
  async function loadOutbox() { const list = byId('outbox-list'); const jobs = (await app.api('/api/admin/outbox?limit=100')).data; list.innerHTML = jobs.length ? jobs.map((job) => `<article class="record-card"><div><h3>Job #${job.id}</h3><p>Notification #${job.notification_id} · ${esc(job.channel)} · ${esc(job.recipient_reference)}</p></div><span class="status-text ${esc(job.status)}">${esc(job.status)}</span>${job.status === 'FAILED' ? `<button class="button button-secondary" data-outbox="retry" data-id="${job.id}">Retry</button>` : ''}${['PENDING','FAILED'].includes(job.status) ? `<button class="button button-danger" data-outbox="cancel" data-id="${job.id}">Cancel</button>` : ''}</article>`).join('') : '<p class="empty-state">No outbox jobs.</p>'; }
  async function loadOperations() { const data = (await app.api('/api/admin/operations/metrics')).data; byId('operations-metrics').innerHTML = `<article class="record-card"><div><h3>Application health</h3><p>Schema version ${data.gauges.schema_version} · Uptime ${data.gauges.process_uptime_seconds}s</p><p>${data.counters.requests} requests · ${data.counters.errors} errors · ${data.gauges.outbox_pending} pending · ${data.gauges.outbox_failed} failed</p></div></article>`; }
  byId('recovery-form').addEventListener('submit', async (event) => { event.preventDefault(); const message = byId('recovery-message'); try { await app.api('/api/auth/recovery/complete', { method: 'POST', body: JSON.stringify({ token: byId('recovery-token').value, password: byId('recovery-password').value }) }); event.currentTarget.reset(); message.textContent = 'Password reset. Sign in with the new password.'; } catch (error) { message.textContent = error.message; } });
  byId('user-admin-list').addEventListener('click', async (event) => { const button = event.target.closest('[data-user-action]'); if (!button) return; recoveryTrigger = button; try { if (button.dataset.userAction === 'role') { const role=byId(`user-role-${button.dataset.id}`).value; await app.api(`/api/admin/users/${button.dataset.id}`, { method:'PATCH', body:JSON.stringify({role}) }); await loadUsers(); } if (button.dataset.userAction === 'toggle') { await app.api(`/api/admin/users/${button.dataset.id}`, { method: 'PATCH', body: JSON.stringify({ status: button.dataset.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE' }) }); await loadUsers(); } if (button.dataset.userAction === 'security') { await app.api(`/api/admin/users/${button.dataset.id}`, { method:'PATCH', body:JSON.stringify({security_status:button.dataset.security === 'ACTIVE' ? 'LOCKED' : 'ACTIVE'}) }); await loadUsers(); } if (button.dataset.userAction === 'revoke') { await app.api(`/api/admin/users/${button.dataset.id}/revoke`, { method: 'POST' }); await loadUsers(); } if (button.dataset.userAction === 'recover') { const result = await app.api(`/api/admin/users/${button.dataset.id}/recovery`, { method: 'POST' }); byId('recovery-output').textContent = result.data.recovery_token; byId('recovery-dialog').showModal(); } } catch (error) { app.showWorkspaceMessage(error.message, true); } });
  byId('recovery-dialog').addEventListener('close', () => { byId('recovery-output').textContent = ''; recoveryTrigger?.focus(); });
  byId('recovery-dialog').addEventListener('cancel', () => { byId('recovery-output').textContent = ''; });
  byId('outbox-list').addEventListener('click', async (event) => { const button = event.target.closest('[data-outbox]'); if (!button) return; try { await app.api(`/api/admin/outbox/${button.dataset.id}/${button.dataset.outbox}`, { method: 'POST' }); await loadOutbox(); } catch (error) { app.showWorkspaceMessage(error.message, true); } });
  const previousLoad = window.diuPhase4.load; window.diuPhase4.load = async (view) => { await previousLoad(view); await load(view); };
})();
